CREATE DATABASE IF NOT EXISTS thoughts_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE thoughts_db;

CREATE TABLE IF NOT EXISTS thoughts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  text VARCHAR(280) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

